### ISSUE TITLE
Remember to give proper authorship credit.

### ISSUE THREAD

**Issue by BKaperick** [haidmoham/PCS_Solutions#1]
A lot of these solutions seem to draw pretty heavily (or in some cases, identically) from published solutions on pcs from Harrison, Peter and others.  I think for the sake of full disclosure, it'd be best to make their contributions clear in the header of these files.

I only bring this up since I notice your website links back to your github page, and I feel it would be misleading to suggest that the code is entirely your own work in this context.

The header "Created by mo on x/x/xxxx" does not appropriately describe the nature of the work.

**Comment by haidmoham** [comment]
I completely forgot about this, will change ASAP.
